name: main

on:
  push:
    branches: [main]
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Deploy to production
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          JWT_SECRET: ${{ secrets.TOKEN_SECRET }}
        run: yarn deploy
